name: CI
on:
  pull_request:
    branches: [main] # Запуск только при создании PR в main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: echo "Running tests..." # Замени на реальную команду тестов, если она есть